### ISSUE TITLE
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

### ISSUE THREAD

**Issue by RCheese** [ROCmSoftwarePlatform/rccl#111]
subj

Arch Linux

**Comment by wenkaidu** [comment]
More details?

**Comment by codecor-cn** [comment]
use  --hip-clang ?

**Comment by wenkaidu** [comment]
Default compiler is hip-clang from ROCm 3.5. We need to change build instructions to this:
CXX=/opt/rocm/bin/hipcc cmake ..
