### ISSUE TITLE
[Feature]: Profiling

### ISSUE THREAD

**Issue by tks2004** [ROCmSoftwarePlatform/rccl#1207]
### Suggestion Description

Is there any tool or an option which provides the compute time of the reduction operation

### Operating System

Ubuntu

### GPU

MI250A

### ROCm Component

RCCL

**Comment by tks2004** [comment]
Could someone respond to this

**Comment by gilbertlee-amd** [comment]
Hi @tks2004 - Sorry for the late reply.

There's no way to isolate just the compute time for the reduction operation, as the arithmetic is generally not the bottleneck, and it's tied closely to the communication.

If you would like to get some in-depth profiling, I'd recommend trying using[ NPKit](https://github.com/ROCm/rccl?tab=readme-ov-file#npkit).
