### ISSUE TITLE
Inquiry About RCCL Version 6.2.X Release Date

### ISSUE THREAD

**Issue by 17113325** [ROCmSoftwarePlatform/rccl#1235]
Dear developers,
Hello!
I am currently working on a development project involving RCCL and would like to inquire about the estimated release date for version 6.2.X. Any information you could provide would greatly assist in the progress of my project.
Thank you very much for your time and support. I look forward to your reply.

**Comment by corey-derochie-amd** [comment]
Hello, @17113325 .

ROCm 6.2.0 is now available. Please find the documentation here: https://rocm.docs.amd.com/en/docs-6.2.0/
