### ISSUE TITLE
Compute time in the reduction operation

### ISSUE THREAD

**Issue by tks2004** [ROCmSoftwarePlatform/rccl#1267]
### Problem Description

Hi, We are in need to time the compute of the reduction operation, Is there any environment variable or any process to get the time of the compute in the allreduce collective

### Operating System

Ubuntu

### CPU

EPYC77603

### GPU

AMD Instinct MI250X

### ROCm Version

ROCm 6.1.0

**Comment by gilbertlee-amd** [comment]
No - no such environment variable exists.  
Aside from NPKit, which I suggested previously, you could get the overall time for the AllReduce by wrapping it between two hipEvents, calling hipEventSynchronize, then getting the elapsed time using hipEventElapsedTime.

**Comment by tks2004** [comment]
> No - no such environment variable exists. Aside from NPKit, which I suggested previously, you could get the overall time for the AllReduce by wrapping it between two hipEvents, calling hipEventSynchronize, then getting the elapsed time using hipEventElapsedTime.

Ok. Thanks
