### ISSUE TITLE
computeColl never defined

### ISSUE THREAD

**Issue by ryanhankins** [ROCmSoftwarePlatform/rccl#1405]
This appears to be a leftover static declaration of computeColl(). Should it be removed?

https://github.com/ROCm/rccl/blob/develop/src/enqueue.cc#L46

**Comment by ppanchad-amd** [comment]
Hi @ryanhankins. Internal ticket has been created to assist with your issue. Thanks!

**Comment by darren-amd** [comment]
Hi @ryanhankins,

Thanks for pointing that out, I have submitted a PR here with the fixes you highlighted: https://github.com/ROCm/rccl/pull/1406.
