### ISSUE TITLE
Remove build system dependence on ROCm hardware

### ISSUE THREAD

**Issue by sabreshao** [ROCmSoftwarePlatform/rccl#2]
https://github.com/ROCmSoftwarePlatform/rccl/blob/7b59e9396310cce0adeb95831b820c882e9bb5f9/src/Makefile#L7
Add "-amdgpu-target=gfx803 -amdgpu-target=gfx900" in line7 and line11 so rccl can build without ROCm hardware.

**Comment by adityaatluri** [comment]
Did you test it?

**Comment by sabreshao** [comment]
@adityaatluri  Yes.

**Comment by sabreshao** [comment]
Any updates?

**Comment by adityaatluri** [comment]
https://github.com/ROCmSoftwarePlatform/rccl/commit/092b6801f35d26a56418aa889a6fcf82eeb78545 fixes
