### ISSUE TITLE
What is difference between rccl and nccl?

### ISSUE THREAD

**Issue by Isaacleee** [ROCmSoftwarePlatform/rccl#202]
Hi

I have one question. When I saw the source code of rccl, it looks similar with nccl, are there any diffrece between two?

**Comment by saadrahim** [comment]
RCCL is a port of NCCL for AMD GPU platforms. It is based on the open source NCCL code with optimizations specific for AMD GPUs.

**Comment by Isaacleee** [comment]
thanks, but I wanted to know how RCCL is implemented

Specifically, can I run any NCCL compatible program on RCCL?

**Comment by saadrahim** [comment]
The libraries are API compatible. It is possible to port a NCCL compatible program to RCCL. With any port of software between platforms, there is some integration work required. In the best case, it may be as simple as linking against the RCCL library. Realistically, I think there will some coding effort on the part of your software vendor. Can you provide some information on the application you are thinking of?

**Comment by Isaacleee** [comment]
Oh it's okay. I just want to know what difference between nccl and rccl. 

one more questions,  if nccl and rccl have same algorithm in allreduce, in nccl, the result of data was save to directly to next gpu after reduction. I want to know how they didn't the access the local memory after they access to remote gpu...

I want to know exactly what hardware pass. For example, CU -> Cache -> DMA -> interconnection -> remote gpu memory, this is about terms of hardware and path of right after result data.

**Comment by saadrahim** [comment]
@wenkaidu and @gilbertlee-amd are better equipped to answer your questions.

**Comment by wenkaidu** [comment]
The data path is almost identical between RCCL and NCCL: If two GPUs don't have P2P access, then buffer is allocated in system memory. If two GPUs have P2P access either throughput PCIe or XGMI, one GPU will then write data to another GPU's VRAM directly.
In case of RCCL, the VRAM is allocated as "fine grain", which L2 cache is bypassed.

**Comment by Isaacleee** [comment]
Thanks   :)
