### ISSUE TITLE
param not work for me

### ISSUE THREAD

**Issue by dearsxx0918** [ROCmSoftwarePlatform/rccl#291]
I tried --display-topo, seems not work for me this time.
The command I use: `/mpirun  -n 2   -mca pml ucx -x UCX_NET_DEVICES=eno1,eno2  --display-topo -display-map -host mgpu1:1,mgpu2:1 --display-allocation -output-filename log.log ./all_reduce_perf -g 2 -b 100 -e 4000000`

Anybody know this?

**Comment by dearsxx0918** [comment]
Anyone can take a look at this? Thanks！

**Comment by gilbertlee-amd** [comment]
I'm not 100% familiar with what "--display-topo" does, but that's part of MPI, and not RCCL.  I'll try it out on some machines, but I'm not sure if I'll be able to answer why it doesn't work for you.

**Comment by dearsxx0918** [comment]
> I'm not 100% familiar with what "--display-topo" does, but that's part of MPI, and not RCCL. I'll try it out on some machines, but I'm not sure if I'll be able to answer why it doesn't work for you.
Thanks, I've found another way to workaround this, so just close this if you are also agree.
Thanks again for your time.

**Comment by gilbertlee-amd** [comment]
OK - I'll close this for now due to that it's not actually RCCL related.
