### ISSUE TITLE
RCCL with multi IB ports

### ISSUE THREAD

**Issue by learner321** [ROCmSoftwarePlatform/rccl#308]
Env: ROCm 3.9

RCCL may not support two IB ports for one rank, like `NCCL_IB_HCA=mlx5_0:1,mlx5_1:1`. If I want to implement that, how should I do. `No plugin found (librccl-net.so), using internal implementation`, for NCCL, one of its plugins like [https://github.com/aws/aws-ofi-nccl](url), how about the RCCL. And nv_peer_memory module is needed for NCCL supported by MLX for GPUDirect RDMA, how about RCCL, I think this module may not be available for RCCL.

Thanks :)

**Comment by wenkaidu** [comment]
We found that using 2 IB ports on same NIC didn't improve performance. Also there are some configurations one IB port is connected to high speed switch, another IB port is connected to a lower speed switch used for management purpose. Thus RCCL implemented some logic to use only one high speed port. However, this logic is only applied on Rome machines at this time.

Regarding network plugin, it should be straight forward to hipify from NCCL plugin. Let us know if you have any issue porting the plugin. Maybe we can help.

**Comment by learner321** [comment]
For 2 IB ports on different NIC,  connected by two PCIE x16, how about the bandwidth like `NCCL_IB_HCA=mlx5_0,mlx5_1`. Such as this topo, two GPUs with one NIC , eight GPUs total in the server, for ring allreduce,  there may be only two ports with dataflow if just one IB port for one mpi process. For RCCL plugin, you mean that I should hipify the NCCL plugin like [https://github.com/aws/aws-ofi-nccl](url).

Thanks :)

**Comment by wenkaidu** [comment]
The overall multi-node throughput will be the lowest of intra-node and inter-node throughput. We can have 2 rings from the example topo you mentioned:
1st ring: NIC0->GPU0->GPU1->..->.GPU7->NIC1
2nd ring: NIC1->GPU7->GPU6...->GPU0->NIC0
Suppose NIC throughput is 10GB/s, GPU to GPU throughput is 20GB/s, then each ring we get 10GB/s. Two rings together we get 20GB/s.
Yes, you can hipify plug-ins like aws-ofi-nccl.
