### ISSUE TITLE
validation tests might not be reporting mismatches

### ISSUE THREAD

**Issue by jeffdaily** [ROCmSoftwarePlatform/rccl#31]
The `validate` function returns a bool, however, not one of the uses of the function ever checks the return value to indicate a failure.

**Comment by adityaatluri** [comment]
Right. There are two features with `validate` function.
1. It prints if there is a mismatch between expected and evaluated data.
2. It returns a boolean if there is a mismatch and prints out info about the mismatch.

I decided to use just the first one. Second option can be used too, the error log will be unaffected.
