### ISSUE TITLE
This is a question: RCCL seems compatible with HIP, But can I use it with ROCm+OpenCL?

### ISSUE THREAD

**Issue by avidov** [ROCmSoftwarePlatform/rccl#327]
Question was previously asked  [here](https://github.com/ROCmSoftwarePlatform/rccl/issues/289#issuecomment-720182350) without reply yet. 

I'm working to add GPU to GPU communication for ML library that uses OpenCL when using AMD.
Can I use RCCL?
RCCL uses HIP streams, while my library is using OpenCL streams. Are they compatible / synchronized ?
Can one stream be can be used on the CPU as both HIP and OpenCL stream?

**Comment by gilbertlee-amd** [comment]
Hi - I'm not sure what you mean by OpenCL streams - are  you referring to OpenCL command-queues?
Either way, HIP is not interoperable with OpenCL.

**Comment by avidov** [comment]
Thank you!
Is there any solution for AMD GPU-2-GPU communication when using OpenCL ?

**Comment by gilbertlee-amd** [comment]
Hi @avidov,

Sorry - but I'm not familiar with GPU to GPU communications with OpenCL.
Perhaps you could ask here: 
https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime

Or it might be referenced here:
https://rocmdocs.amd.com/en/latest/Programming_Guides/Opencl-programming-guide.html
