### ISSUE TITLE
Change number of workitems launched in kernels

### ISSUE THREAD

**Issue by adityaatluri** [ROCmSoftwarePlatform/rccl#33]
Hi,
This is an obvious optimization. Currently, a copy or reduction kernel operating on remote buffers are launched with number of workitems = number of elements in buffer. We found that using a single workgroup with 1024 or 512 or 256 workitems can achieve same bandwidth.
So, change the current implementation of kernels to use a single workgroup to do reduction ops and data transfers.

**Comment by wenkaidu** [comment]
From my experiment on allgather, by changing to single workgroup reduced performance to about a third of original throughput: https://github.com/wenkaidu/rccl/commit/b4b7c437c881d3b90c5e8a30bd0f7ba10a4c5b6f

Further optimization must be done to achieve same bandwidth.

**Comment by wenkaidu** [comment]
Performance improved with 64b copying:
https://github.com/wenkaidu/rccl/commit/84b661440e2ba0e3b08758026ff61e6d5be2c0bd
