### ISSUE TITLE
bug，I can't find why this bug appears, I hope to ask for help

### ISSUE THREAD

**Issue by nmanhong** [ROCmSoftwarePlatform/rccl#360]
When I use "make -j1", these errors are prompted
“[  1%] Building CXX object CMakeFiles/rccl.dir/src/collectives/device/all_reduce.cpp.o
LLVM ERROR: out of memory
Allocation failed
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/rocm/llvm/bin/clang-12 -cc1 -mllvm --amdhsa-code-object-version=4 -triple amdgcn-amd-amdhsa -aux-triple mips64el-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -main-file-name all_reduce.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fdenormal-fp-math-f32=preserve-sign,preserve-sign -fno-rounding-math -mconstructor-aliases -aux-target-cpu mips64r2 -aux-target-feature -noabicalls -fcuda-is-device -fgpu-rdc -fcuda-allow-variadic-functions -fvisibility hidden -fapply-global-visibility-to-externs -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/hip.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/ocml.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/ockl.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_daz_opt_on.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_unsafe_math_off.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_finite_only_off.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_correctly_rounded_sqrt_on.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_wavefrontsize64_on.bc -mlink-builtin-bitcode /opt/rocm/amdgcn/bitcode/oclc_isa_version_803.bc -target-cpu gfx803 -fno-split-dwarf-inlining -debugger-tuning=gdb -resource-dir /opt/rocm/llvm/lib/clang/12.0.0 -internal-isystem /opt/rocm/llvm/lib/clang/12.0.0/include/cuda_wrappers -internal-isystem /opt/rocm/include -include __clang_hip_runtime_wrapper.h -isystem /opt/rocm/llvm/lib/clang/12.0.0/include/.. -isystem /opt/rocm/hsa/include -isystem /opt/rocm/include -D __HIP_ROCclr__ -D __HIP_ROCclr__ -D ENABLE_COLLTRACE -D __HIP_PLATFORM_HCC__=1 -D __HIP_ROCclr__=1 -D rccl_EXPORTS -I /home/loongson/ROCm/rccl/build -I /home/loongson/ROCm/rccl/src -I /home/loongson/ROCm/rccl/src/include -I /home/loongson/ROCm/rccl/src/collectives -I /home/loongson/ROCm/rccl/src/collectives/device -c-isystem /usr/local/openblas/include -c-isystem /usr/local/deployment_tools/inference_engine/include -c-isystem /usr/local/openblas/include -c-isystem /usr/local/deployment_tools/inference_engine/include -c-isystem . -cxx-isystem /opt/rocm/rocclr/include/compiler/lib/include -cxx-isystem /opt/rocm/rocclr/include/elf -cxx-isystem /opt/rh/devtoolset-7/root/usr/include/c++/7/mips64el-redhat-linux -cxx-isystem /opt/rh/devtoolset-7/root/usr/include/c++/7 -cxx-isystem /usr/local/openblas/include -cxx-isystem /usr/local/deployment_tools/inference_engine/include -cxx-isystem /opt/rocm/rocclr/include/compiler/lib/include -cxx-isystem /opt/rocm/rocclr/include/elf -cxx-isystem /opt/rh/devtoolset-7/root/usr/include/c++/7/mips64el-redhat-linux -cxx-isystem /opt/rh/devtoolset-7/root/usr/include/c++/7 -cxx-isystem /usr/local/openblas/include -cxx-isystem /usr/local/deployment_tools/inference_engine/include -cxx-isystem . -internal-isystem /usr/local/include -internal-isystem /opt/rocm/llvm/lib/clang/12.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /usr/local/include -internal-isystem /opt/rocm/llvm/lib/clang/12.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wno-format-nonliteral -std=c++14 -fdeprecated-macro -fno-autolink -fdebug-compilation-dir /home/loongson/ROCm/rccl/build -ferror-limit 19 -fhip-new-launch-api -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -fcuda-allow-variadic-functions -faddrsig -o /tmp/all_reduce-gfx803-a94c35.bc -x hip /home/loongson/ROCm/rccl/build/src/collectives/device/all_reduce.cpp 
1.	<eof> parser at end of file
2.	Per-module optimization passes
3.	Running pass 'CallGraph Pass Manager' on module '/home/loongson/ROCm/rccl/build/src/collectives/device/all_reduce.cpp'.
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
/opt/rocm/llvm/bin/clang-12(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamEi+0x40)[0x121e1cd00]
clang-12: error: unable to execute command: Aborted
clang-12: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 12.0.0 (/home/loongson/ROCm/llvm-project/clang 91c055b1c52a830317cae78986d0d74e433864c6)
Target: mips64el-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
clang-12: note: diagnostic msg: Error generating preprocessed source(s).
CMakeFiles/rccl.dir/build.make:81: recipe for target 'CMakeFiles/rccl.dir/src/collectives/device/all_reduce.cpp.o' failed
make[2]: *** [CMakeFiles/rccl.dir/src/collectives/device/all_reduce.cpp.o] Error 254
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/rccl.dir/all' failed
make[1]: *** [CMakeFiles/rccl.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2
”
When I use "make -j4", the error message is prompted
”llvm-objcopy: error: invalid symbol index: 119014656
/opt/rocm/llvm/bin/clang-offload-bundler: error: 'llvm-objcopy' tool failed
clang-12: error: clang-offload-bundler command failed with exit code 1 (use -v to see invocation)
CMakeFiles/rccl.dir/build.make:94: recipe for target 'CMakeFiles/rccl.dir/src/collectives/device/all_gather.cpp.o' failed
make[2]: *** [CMakeFiles/rccl.dir/src/collectives/device/all_gather.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
llvm-objcopy: error: invalid symbol index: 119014656
/opt/rocm/llvm/bin/clang-offload-bundler: error: 'llvm-objcopy' tool failed
clang-12: error: clang-offload-bundler command failed with exit code 1 (use -v to see invocation)
CMakeFiles/rccl.dir/build.make:120: recipe for target 'CMakeFiles/rccl.dir/src/collectives/device/broadcast.cpp.o' failed
make[2]: *** [CMakeFiles/rccl.dir/src/collectives/device/broadcast.cpp.o] Error 1
“
 and it is this again. I can't find the reason for these errors and where they are

**Comment by gilbertlee-amd** [comment]
Hi @nmanhong,

Were you able to resolve this issue?

**Comment by gilbertlee-amd** [comment]
Closed for now.  Feel free to reopen with details.
