### ISSUE TITLE
Performance for multi process in one node with PCIE Switch

### ISSUE THREAD

**Issue by learner321** [ROCmSoftwarePlatform/rccl#362]
Two processes, and each process control one GPU. 

1. Two GPUs are connected via one PCIE Switch.  
`build/all_reduce_perf --minbytes=16 --maxbytes=262144000 --parallel_init=0 --warmup_iters=10 --stepfactor=2 --iters=1000`

       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
          16             4   float     sum    25.81    0.00    0.00  0e+00    26.80    0.00    0.00  0e+00
          32             8   float     sum    26.77    0.00    0.00  0e+00    26.74    0.00    0.00  0e+00
          64            16   float     sum    27.03    0.00    0.00  0e+00    27.05    0.00    0.00  0e+00
         128            32   float     sum    27.05    0.00    0.00  0e+00    27.02    0.00    0.00  0e+00
         256            64   float     sum    27.12    0.01    0.01  0e+00    27.16    0.01    0.01  0e+00
         512           128   float     sum    27.39    0.02    0.02  0e+00    27.36    0.02    0.02  0e+00
        1024           256   float     sum    27.74    0.04    0.04  0e+00    27.68    0.04    0.04  0e+00
        2048           512   float     sum    28.33    0.07    0.07  0e+00    28.30    0.07    0.07  0e+00
        4096          1024   float     sum    43.39    0.09    0.09  0e+00    43.29    0.09    0.09  0e+00
        8192          2048   float     sum    30.88    0.27    0.27  0e+00    30.85    0.27    0.27  0e+00
       16384          4096   float     sum    32.19    0.51    0.51  0e+00    32.14    0.51    0.51  0e+00
       32768          8192   float     sum    42.48    0.77    0.77  0e+00    42.40    0.77    0.77  0e+00
       65536         16384   float     sum    62.45    1.05    1.05  0e+00    62.29    1.05    1.05  0e+00
       131072         32768   float     sum    101.5    1.29    1.29  0e+00    101.4    1.29    1.29  0e+00
       262144         65536   float     sum    103.6    2.53    2.53  0e+00    103.3    2.54    2.54  0e+00
       524288        131072   float     sum    171.3    3.06    3.06  0e+00    171.4    3.06    3.06  0e+00
       1048576        262144   float     sum    313.0    3.35    3.35  0e+00    313.1    3.35    3.35  0e+00
       2097152        524288   float     sum    593.6    3.53    3.53  0e+00    593.4    3.53    3.53  0e+00
       4194304       1048576   float     sum   1154.7    3.63    3.63  0e+00   1153.1    3.64    3.64  0e+00
       8388608       2097152   float     sum   2264.0    3.71    3.71  0e+00   2266.8    3.70    3.70  0e+00
       16777216       4194304   float     sum   4463.2    3.76    3.76  0e+00   4463.6    3.76    3.76  0e+00
       33554432       8388608   float     sum   8844.7    3.79    3.79  0e+00   8840.8    3.80    3.80  0e+00

2. Two GPUs are connected via CPU without PCIE Switch.  

       size         count    type   redop     time   algbw   busbw  error     time   algbw   busbw  error
        (B)    (elements)                     (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
          16             4   float     sum    43.43    0.00    0.00  0e+00    43.32    0.00    0.00  0e+00
          32             8   float     sum    43.26    0.00    0.00  0e+00    43.25    0.00    0.00  0e+00
          64            16   float     sum    43.25    0.00    0.00  0e+00    43.32    0.00    0.00  0e+00
         128            32   float     sum    43.29    0.00    0.00  0e+00    43.28    0.00    0.00  0e+00
         256            64   float     sum    43.48    0.01    0.01  0e+00    43.39    0.01    0.01  0e+00
         512           128   float     sum    43.72    0.01    0.01  0e+00    43.75    0.01    0.01  0e+00
        1024           256   float     sum    44.22    0.02    0.02  0e+00    44.20    0.02    0.02  0e+00
        2048           512   float     sum    45.04    0.05    0.05  0e+00    45.01    0.05    0.05  0e+00
        4096          1024   float     sum    49.23    0.08    0.08  0e+00    49.60    0.08    0.08  0e+00
        8192          2048   float     sum    49.88    0.16    0.16  0e+00    49.97    0.16    0.16  0e+00
       16384          4096   float     sum    57.50    0.28    0.28  0e+00    57.47    0.29    0.29  0e+00
       32768          8192   float     sum    72.37    0.45    0.45  0e+00    72.35    0.45    0.45  0e+00
       65536         16384   float     sum    104.0    0.63    0.63  0e+00    104.0    0.63    0.63  0e+00
       131072         32768   float     sum    170.3    0.77    0.77  0e+00    170.1    0.77    0.77  0e+00
       262144         65536   float     sum    92.33    2.84    2.84  0e+00    92.37    2.84    2.84  0e+00
       524288        131072   float     sum    132.0    3.97    3.97  0e+00    132.1    3.97    3.97  0e+00
       1048576        262144   float     sum    223.4    4.69    4.69  0e+00    223.8    4.68    4.68  0e+00
       2097152        524288   float     sum    381.5    5.50    5.50  0e+00    381.5    5.50    5.50  0e+00
       4194304       1048576   float     sum    700.5    5.99    5.99  0e+00    698.8    6.00    6.00  0e+00
       8388608       2097152   float     sum   1370.1    6.12    6.12  0e+00   1366.8    6.14    6.14  0e+00
       16777216       4194304   float     sum   2640.7    6.35    6.35  0e+00   2642.4    6.35    6.35  0e+00
       33554432       8388608   float     sum   5169.0    6.49    6.49  0e+00   5163.0    6.50    6.50  0e+00

I think 1 and 2 does not achive a good performance for PCIE Gen3 x16, and lower performance achived when connected with one PCIE Switch.

**Comment by learner321** [comment]
I find that `p2pTranport` is skipped because of `hasFineGrainVramPcie()`. For my current understanding, the memory is pinned memory in host side if use `hipExtMallocWithFlags((void**)&ptr, sizeof(int), hipDeviceMallocFinegrained`. If i just want to move the data from one GPU'memory to anther's, why not use p2p or ipc?

**Comment by gilbertlee-amd** [comment]
Due to how the PCIe standard potentially allows out-of-order transfers, you'll need an extra environment variable flag in order to not skip p2pTransport: HSA_FORCE_FINE_GRAIN_PCIE=1.    This isn't required on XGMI-connected GPUs, but must be used in order to enable p2pTransport for RCCL.  Thanks for the question - this wasn't well documented in our README, so we'll be updating that.

Could you try again with HSA_FORCE_FINE_GRAIN_PCIE=1?

**Comment by learner321** [comment]
Thank you, got it. If HSA_FORCE_FINE_GRAIN_PCIE=1, hipExtMallocWithFlags will return hipSuccess.
