### ISSUE TITLE
"Cannot find Symbol" for a program linked with -fgpu-rdc

### ISSUE THREAD

**Issue by ex-rzr** [ROCmSoftwarePlatform/rccl#397]
The original program uses MPI with one GPU per process and some NCCL operations.
A simple test with one process-one thread-multiple GPUs: [rccl_rdc.zip](https://github.com/ROCmSoftwarePlatform/rccl/files/6684812/rccl_rdc.zip) (zip because GitHub doesn't allow to upload .cpp)

It works without RDC:
```
hipcc rccl_rdc.cpp -o rccl_rdc -l rccl
AMD_LOG_LEVEL=4 HSA_FORCE_FINE_GRAIN_PCIE=1 ./rccl_rdc
```

But it fails with RDC:
```
hipcc -fgpu-rdc rccl_rdc.cpp -o rccl_rdc -l rccl
AMD_LOG_LEVEL=4 HSA_FORCE_FINE_GRAIN_PCIE=1 ./rccl_rdc
```

```
:3:hip_module.cpp           :590 : 2065834582307 us: 1665178: [7fad85723080] hipExtLaunchMultiKernelMultiDevice ( 0x7fa76806a070, 2, 3 )
:3:devprogram.cpp           :2463: 2065834582494 us: Using Code Object V4.
:1:hip_global.cpp           :68  : 2065834582995 us: Cannot find Symbol with name: _Z42ncclKernel_SendRecv_RING_SIMPLE_Sum_int8_t12ncclWorkElem 

"Cannot find Symbol"
Aborted (core dumped)
```
Full log: [rccl_rdc.log](https://github.com/ROCmSoftwarePlatform/rccl/files/6684792/rccl_rdc.log)

As you can see I don't even need to really use a separate compilation of multiple files and then link with them into a single binary (as it's done for the original program).

**Comment by wenkaidu** [comment]
We are looking into this issue and will update you later. Thanks

**Comment by yxsamliu** [comment]
This issue should be fixed by https://reviews.llvm.org/D106571

**Comment by gilbertlee-amd** [comment]
Should be fixed in latest releases
