### ISSUE TITLE
When the Google test root of broadcast is 1/2/3, what is the problem of use case stuck?

### ISSUE THREAD

**Issue by xiabo123** [ROCmSoftwarePlatform/rccl#427]
@wenkaidu 
![image](https://user-images.githubusercontent.com/40659418/133567573-bf70b5ee-ff4b-467a-823c-66c3d2d64d23.png)

**Comment by wenkaidu** [comment]
Which version of RCCL is this? You may enable RCCL kernel trace which can tell you which kernel may be stuck.

**Comment by doctorcolinsmith** [comment]
@xiabo123 Along with the RCCL version, can you please also add which GPU and OS you are using?  Thanks.

**Comment by xiabo123** [comment]
RCCL version 2.9.9+hip4.0

**Comment by gilbertlee-amd** [comment]
Please try this with a newer version of RCCL and re-open a ticket if this still applies.
