### ISSUE TITLE
On rocm4.0, What are the possible reasons for the following errors? Drive?

### ISSUE THREAD

**Issue by xiabo123** [ROCmSoftwarePlatform/rccl#456]
![image](https://user-images.githubusercontent.com/40659418/139799433-40a405fc-c445-4f27-8b08-8e4097355a8f.png)

**Comment by gilbertlee-amd** [comment]
This appears to be a topology detection issue.  Would you be able to provide more information about the setup?

**Comment by xiabo123** [comment]
Instead of using RCCL in ROCM, recompile with RCCL in GitHub library.

**Comment by xiabo123** [comment]
Thank you.
