### ISSUE TITLE
Does rccl support inter node communication without IB？

### ISSUE THREAD

**Issue by hanjiemicro** [ROCmSoftwarePlatform/rccl#474]
FYI

**Comment by gilbertlee-amd** [comment]
Yes.  It should drop back to sockets-based communication

**Comment by hanjiemicro** [comment]
Could you help to give some examples~

**Comment by hanjiemicro** [comment]
Hi gilbertlee-amd:
I tried tcp socket with below code.Below code is running on slave machine, The init_method: tcp is from master IP，but it still failed. 
$ more test.py 
import torch.distributed as dist
import torch.utils.data.distributed
dist.init_process_group(backend='nccl', init_method="tcp://192.168.100.101:29542", rank=0, world_size=1)
print("init done")

**Comment by hanjiemicro** [comment]
I use rccl(rocm-4.0.x) in my local.
BTW, I noticed there has variable: NCCL_CROSS_NIC, which controls whether NCCL should allow rings/trees to use different NICs, causing inter-node communication to use different NICs on different nodes.
The crossNic function was found in master, but empty in rocm-4.0.x branch.  I wonder know whether the NCCL_CROSS_NIC switch was used both for IB and socket based inter-node communication?
![image](https://user-images.githubusercontent.com/66557467/143412032-4c1ef98a-84a3-47ce-b8b8-927ef8543aa9.png)

**Comment by gilbertlee-amd** [comment]
I'm not completely familiar with how pyTorch integrates RCCL, however should world_size only be 1 when you are using a slave / master?

NCCL_CROSS_NIC applies to any NIC-based communication (checked during ring/tree creation), and doesn't just apply to IB / sockets.
