### ISSUE TITLE
How to use socketdirect technology similar to UCX in UCX_ IB_ ADDR_ TYPE=ib_ global？

### ISSUE THREAD

**Issue by xiabo123** [ROCmSoftwarePlatform/rccl#480]
How to use socketdirect technology similar to UCX in UCX_ IB_ ADDR_ TYPE=ib_ global？

**Comment by gilbertlee-amd** [comment]
Sorry - I don't have expertise in what UCX_IB_ADDR_TYPE=ib_global does exactly - could you elaborate on what you mean by socketdirect technology?

**Comment by xiabo123** [comment]
UCX is used in nccl. As the website says."https://github-wiki-see.page/m/Mellanox/nccl-rdma-sharp-plugins/wiki/NCCL-UCX-plugin". Setting the environment variable UCX_ IB_ ADDR_ TYPE=ib_ global.

**Comment by wenkaidu** [comment]
You can find RCCL plugin here: https://github.com/ROCmSoftwarePlatform/rccl-rdma-sharp-plugins. The main purpose was for SHARP, UCX support has not been tested. Please feel free to test and let us know your results.
