### ISSUE TITLE
 kernel function is always sendrecv

### ISSUE THREAD

**Issue by xiabo123** [ROCmSoftwarePlatform/rccl#505]
https://github.com/ROCmSoftwarePlatform/rccl/pull/218

During the performance analysis of this modification, the kernel function is always sendrecv. Is there any way to know which kernel function is called?

**Comment by wenkaidu** [comment]
funcIndex field of ncclWorkElem indicates kernel function to be called

**Comment by xiabo123** [comment]
Yes, but with chrome://tracing/ When performing performance analysis, the function name is sendrecv, which seems very inconvenient. 
As shown below：
![3d2277bcc31b7734ad7156770872ca3](https://user-images.githubusercontent.com/40659418/155444654-34731cfc-378e-4b09-af8c-450965b9f519.png)

**Comment by gilbertlee-amd** [comment]
Sorry for the late reply.
Yes - this is due to how collective group calls are handled - a single kernel is launched, and then differentiation is done within the kernel.
