### ISSUE TITLE
The question: is there an example of direct GPU-to-GPU send and receive operations?

### ISSUE THREAD

**Issue by vasslavich** [ROCmSoftwarePlatform/rccl#521]
Hello!
Thank you, colleagues, for a great library!

I'd like to try to work with a direct GPU-to-GPU send and receive operations. Is there any example (or test) in the repository?

**Comment by gilbertlee-amd** [comment]
There's also an example within the AllToAll collective, which uses ncclSend/ncclRecv under the hood:
https://github.com/ROCmSoftwarePlatform/rccl/blob/develop/src/collectives/all_to_all_api.cc#L28

**Comment by vasslavich** [comment]
Great. Thanks @gilbertlee-amd ! It looks like I need.
