### ISSUE TITLE
Does RCCL support the Infinity Fabric?

### ISSUE THREAD

**Issue by vasslavich** [ROCmSoftwarePlatform/rccl#538]
Hello!
I have MI100 GPUs are interconnected via Infinity Fabric and I'd like to use it with RCCL. The tool TransferBench give me only 27.5 Gbytes per second. Perhaps, does RCCL has any options to turn on Infinity Fabric?
Thanks!

**Comment by vasslavich** [comment]
TransferBench with no arguments shows _PCIE_
And, I looked at kfd configuration, the type is _1_:
`
$ cat /sys/class/kfd/kfd/topology/nodes/0/io_links/5/properties
type 1
....
`

**Comment by gilbertlee-amd** [comment]
Hi @vasslavich, are you sure your GPUs to one another via Infinity Fabric?

**Comment by gilbertlee-amd** [comment]
Could you post the outout of /opt/rocm/bin/rocm-smi --showtopo?
Thanks

**Comment by gilbertlee-amd** [comment]
Based on this output, it looks like your GPUs are connected to one another via PCIe, not Infinity Fabric.  
Hops refers to the number of intermediate steps, which in this case are likely PCIe switchs along the path from one GPU to another.  Weights are somewhat similar to hop values in measuring "distance".  

The topo_expl tool is used to understand how RCCL will establish connections for collectives (e.g. how rings are built) for various (hard-coded) topologies.  Running with no arguments will show supported models, which can be passed in via ./topo_expl -m <mode_id>.

**Comment by vasslavich** [comment]
Hello, @gilbertlee-amd! Thank you!
