### ISSUE TITLE
ROCMConfig.cmake

### ISSUE THREAD

**Issue by computingdolas** [ROCmSoftwarePlatform/rccl#7]
Could not find a package configuration file provided by "ROCM" with any of
  the following names:

    ROCMConfig.cmake
    rocm-config.cmake

  Add the installation prefix of "ROCM" to CMAKE_PREFIX_PATH or set
  "ROCM_DIR" to a directory containing one of the above files.  If "ROCM"
  provides a separate development package or SDK, be sure it has been
  installed.

How to solve this problem.

**Comment by adityaatluri** [comment]
Either you can build from source: https://github.com/RadeonOpenCompute/rocm-cmake
Or install through package manager of a linux distro. For ubuntu: `apt install rocm-cmake`
